spring.application:
  name: portfolio-trading


logging:
  path: logs/
  file: app.log
  level:
    root: INFO
    org.springframework: INFO
    com.example.demo: DEBUG
    org:
      springframework:
        cloud:
          context: INFO

spring:
  datasource:
    url: jdbc:h2:mem:portfolio.db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    username: sa
    password: potfolio-trading-demo
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: embedded
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 10
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

spring.h2:
  console.enabled: true

app:
  portfolio-relative-path: csv/sample-portfolio.csv
  stock-relative-path: csv/sample-stock.csv
  option-relative-path: csv/sample-options.csv

market:
  quote-producer-thread.enabled: true
  broker-dispatch-thread:
    enabled: true
    timeout: 10
  risk-free-interest-rate: 2

